# Generated by Django 4.2.3 on 2023-07-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('origin', models.CharField(blank=True, max_length=128, verbose_name='Origin')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
                ('description', models.TextField(verbose_name='Description')),
                ('time', models.DurationField(verbose_name='Time')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('recipes', models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
